Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
ESP Insights Project commit: a48ea72-dirty
ESP RainMaker Project commit: a48ea72-dirty
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 536, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 541, in parse_int
    return keywords[v.lower()]
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'littlefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 188, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 374, in from_csv
    res.type = res.parse_type(fields[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 422, in parse_type
    return parse_int(strval, TYPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 543, in parse_int
    raise InputError("Value '%s' is not valid. Known keywords: %s" % (v, ', '.join(keywords)))
gen_esp32part.InputError: Value 'littlefs' is not valid. Known keywords: app, data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 363, in <module>
    main()
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshk\esp\v5.3.1\esp-idf\components\partition_table\gen_esp32part.py", line 190, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Value 'littlefs' is not valid. Known keywords: app, data
Please check extra_partition_subtypes.inc file in build/config directory
